<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 3/24/16
 * Time: 6:01 PM
 */

namespace Admin\Controller;


use Common\Tools;
use Home\Api\ApiAppKnow;

class FavoritesController extends AuthController
{
    private $favourite_type;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->favourite_type = array_flip((new ApiAppKnow())->favourite_type);
    }

    public function favoriteList()
    {
        $fansList = M('MemberFavourite')->field(['id','type','obj_id','uid','addtime'])->select();
        foreach($fansList as $k => $v){
            $user_info = D('Member')->field(['userid','mobile'])->where(['userid'=>$v['uid']])->find();
            $fansList[$k]['user_info'] = $user_info;
            $fansList[$k]['type_name'] = $this->favourite_type[$v['type']];
        }
        $this->assign(['fansList'=>$fansList]);
        $this->display();
    }
}