<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 2/23/16
 * Time: 6:00 PM
 */

namespace Admin\Controller;

use Common\Tools;

class SystemController extends AuthController
{
    private $sql_dir;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->sql_dir = APP_ROOT . "/Data/sql/";
    }

    public function index()
    {
        $this->display();
    }

    /**
     * 用户设置
     */
    public function userSetting()
    {
        $this->display();
    }

    /**
     * 数据备份
     */
    public function dataBackup()
    {
        $db_name = C('DB_NAME');
        $D = D();
        if (IS_POST) {
            $select_tables = I("post.select_tables");
            foreach ($select_tables as $k => $v) {
                $tables[] = $v[0];
            }
            $backup_dir = $this->sql_dir . date("Y-m-d H:i:s") . "/";
            $size = Tools\wodrow\TablesBackup::backupTables($tables, $backup_dir);
            echo $size;
            exit();
        }

        $sql = "SHOW TABLES";
        $tables = $D->query($sql);
        $sql = "use information_schema";
        $D->execute($sql);
        foreach ($tables as $k => $v) {
            static $i = 0;
            $table = $v["tables_in_" . C('DB_NAME')];
            if (preg_match("/^" . C('DB_PREFIX') . "/", $table) || preg_match("/^" . C('DATABASE_MALL_TABLE_PREFIX') . "ucenter_/", $table)) {
                // 获取表信息
                $sql = "select concat(round(sum(data_length/1024/1024),2),'MB') as data, table_name, table_rows from tables where table_schema='{$db_name}' and table_name='{$table}'";
                $table_size_info = $D->query($sql);

                $select_tables[$i]['table_name'] = $table_size_info[0]['table_name'];
                $select_tables[$i]['table_size'] = $table_size_info[0]['data'];
                $select_tables[$i]['table_count'] = $table_size_info[0]['table_rows'];
            }
            $i++;
        }
        $D->execute("use {$db_name}");
        $this->assign(['select_tables' => $select_tables]);
        $this->display();
    }

    /**
     * 数据还原
     */
    public function dataReduction()
    {
        $filesnames = scandir($this->sql_dir);
        // 删除备份
        if (I("post.post") == "delete") {
            $dirname = $this->sql_dir . "/" . I("post.dirname");
            echo Tools::delDirAndFile($dirname, 1);
            exit();
        }

        // 还原备份
        if (I("post.post") == "reduction") {
            $M = M();
            $dirname = $this->sql_dir . "/" . I("post.dirname");
            $files = Tools::get_files($dirname);
            $sql = '';
            foreach ($files as $k => $v) {
                $sql .= file_get_contents($v);
            }
            echo $M->execute($sql);
            exit();
        }

        // 展示数据
        krsort($filesnames);
        foreach ($filesnames as $k => $v) {
            if (preg_match("/^\d{4}\-{1}\d{2}\-{1}\d{2}\s{1}\d{2}\:{1}\d{2}\:{1}\d{2}$/", $v)) {
                $backupDir[$k]['name'] = $v;
                $backupDir[$k]['size'] = Tools::getRealSize(Tools::getDirSize($this->sql_dir . "/" . $v));
                $files = Tools::get_files($this->sql_dir . "/" . $v);
                $backupDir[$k]['file_count'] = count($files);
            }
        }
        $this->assign(['backupDir' => $backupDir]);
        $this->display();
    }
}