<?php
/**
 * Created by PhpStorm.
 * User: iredbaby
 * Date: 16-3-25
 * Time: 下午5:18
 */

namespace Common\Model;
use Think\Model\RelationModel;


class MallRelationModel extends RelationModel
{
    protected $tablePrefix;
    protected $connection;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->tablePrefix = C('DATABASE_MALL_TABLE_PREFIX');
        $this->connection = C('DATABASE_MALL');
    }
}